// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: model/student.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentId string `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
}

func (x *StudentRequest) Reset() {
	*x = StudentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_student_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRequest) ProtoMessage() {}

func (x *StudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_student_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRequest.ProtoReflect.Descriptor instead.
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return file_model_student_proto_rawDescGZIP(), []int{0}
}

func (x *StudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetGradesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grades map[string]string `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // map from assignment name to grade option
}

func (x *GetGradesReply) Reset() {
	*x = GetGradesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_student_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGradesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradesReply) ProtoMessage() {}

func (x *GetGradesReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_student_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradesReply.ProtoReflect.Descriptor instead.
func (*GetGradesReply) Descriptor() ([]byte, []int) {
	return file_model_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetGradesReply) GetGrades() map[string]string {
	if x != nil {
		return x.Grades
	}
	return nil
}

type GetCoursesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId []string `protobuf:"bytes,1,rep,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *GetCoursesReply) Reset() {
	*x = GetCoursesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_student_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoursesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesReply) ProtoMessage() {}

func (x *GetCoursesReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_student_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesReply.ProtoReflect.Descriptor instead.
func (*GetCoursesReply) Descriptor() ([]byte, []int) {
	return file_model_student_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoursesReply) GetCourseId() []string {
	if x != nil {
		return x.CourseId
	}
	return nil
}

type ChooseSectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Section   *Section `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	StudentId string   `protobuf:"bytes,2,opt,name=studentId,proto3" json:"studentId,omitempty"`
}

func (x *ChooseSectionRequest) Reset() {
	*x = ChooseSectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_student_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseSectionRequest) ProtoMessage() {}

func (x *ChooseSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_student_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseSectionRequest.ProtoReflect.Descriptor instead.
func (*ChooseSectionRequest) Descriptor() ([]byte, []int) {
	return file_model_student_proto_rawDescGZIP(), []int{3}
}

func (x *ChooseSectionRequest) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

func (x *ChooseSectionRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ChooseSectionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ChooseSectionReply) Reset() {
	*x = ChooseSectionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_student_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseSectionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseSectionReply) ProtoMessage() {}

func (x *ChooseSectionReply) ProtoReflect() protoreflect.Message {
	mi := &file_model_student_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseSectionReply.ProtoReflect.Descriptor instead.
func (*ChooseSectionReply) Descriptor() ([]byte, []int) {
	return file_model_student_proto_rawDescGZIP(), []int{4}
}

func (x *ChooseSectionReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChooseSectionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_model_student_proto protoreflect.FileDescriptor

var file_model_student_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x65, 0x72, 0x65, 0x1a, 0x13, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x0e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x85, 0x01,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x38, 0x0a, 0x06, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x68, 0x65, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x67, 0x72, 0x61, 0x64, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72,
	0x73, 0x65, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3e,
	0x0a, 0x12, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x88,
	0x02, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x68, 0x65, 0x72, 0x65, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x68, 0x65, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x68, 0x65, 0x72, 0x65, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x68, 0x65, 0x72,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x77, 0x61, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x0c, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0d, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x2e, 0x68, 0x65, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x68, 0x65, 0x72, 0x65, 0x2e, 0x43, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_student_proto_rawDescOnce sync.Once
	file_model_student_proto_rawDescData = file_model_student_proto_rawDesc
)

func file_model_student_proto_rawDescGZIP() []byte {
	file_model_student_proto_rawDescOnce.Do(func() {
		file_model_student_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_student_proto_rawDescData)
	})
	return file_model_student_proto_rawDescData
}

var file_model_student_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_model_student_proto_goTypes = []interface{}{
	(*StudentRequest)(nil),       // 0: here.StudentRequest
	(*GetGradesReply)(nil),       // 1: here.GetGradesReply
	(*GetCoursesReply)(nil),      // 2: here.GetCoursesReply
	(*ChooseSectionRequest)(nil), // 3: here.ChooseSectionRequest
	(*ChooseSectionReply)(nil),   // 4: here.ChooseSectionReply
	nil,                          // 5: here.GetGradesReply.GradesEntry
	(*Section)(nil),              // 6: Section
	(*SwapRequest)(nil),          // 7: SwapRequest
	(*emptypb.Empty)(nil),        // 8: google.protobuf.Empty
}
var file_model_student_proto_depIdxs = []int32{
	5, // 0: here.GetGradesReply.grades:type_name -> here.GetGradesReply.GradesEntry
	6, // 1: here.ChooseSectionRequest.section:type_name -> Section
	0, // 2: here.Student.GetCourses:input_type -> here.StudentRequest
	0, // 3: here.Student.GetGrades:input_type -> here.StudentRequest
	7, // 4: here.Student.SubmitSwapRequests:input_type -> SwapRequest
	3, // 5: here.Student.ChooseSection:input_type -> here.ChooseSectionRequest
	2, // 6: here.Student.GetCourses:output_type -> here.GetCoursesReply
	1, // 7: here.Student.GetGrades:output_type -> here.GetGradesReply
	8, // 8: here.Student.SubmitSwapRequests:output_type -> google.protobuf.Empty
	4, // 9: here.Student.ChooseSection:output_type -> here.ChooseSectionReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_student_proto_init() }
func file_model_student_proto_init() {
	if File_model_student_proto != nil {
		return
	}
	file_model_general_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_model_student_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_student_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGradesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_student_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoursesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_student_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseSectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_student_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseSectionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_student_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_student_proto_goTypes,
		DependencyIndexes: file_model_student_proto_depIdxs,
		MessageInfos:      file_model_student_proto_msgTypes,
	}.Build()
	File_model_student_proto = out.File
	file_model_student_proto_rawDesc = nil
	file_model_student_proto_goTypes = nil
	file_model_student_proto_depIdxs = nil
}
