// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StudentClient is the client API for Student service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentClient interface {
	GetCourses(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*GetCoursesReply, error)
	GetGrades(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*GetGradesReply, error)
	SubmitSwapRequests(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ChooseSection(ctx context.Context, in *ChooseSectionRequest, opts ...grpc.CallOption) (*ChooseSectionReply, error)
}

type studentClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentClient(cc grpc.ClientConnInterface) StudentClient {
	return &studentClient{cc}
}

func (c *studentClient) GetCourses(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*GetCoursesReply, error) {
	out := new(GetCoursesReply)
	err := c.cc.Invoke(ctx, "/here.Student/GetCourses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) GetGrades(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*GetGradesReply, error) {
	out := new(GetGradesReply)
	err := c.cc.Invoke(ctx, "/here.Student/GetGrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) SubmitSwapRequests(ctx context.Context, in *SwapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/here.Student/SubmitSwapRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentClient) ChooseSection(ctx context.Context, in *ChooseSectionRequest, opts ...grpc.CallOption) (*ChooseSectionReply, error) {
	out := new(ChooseSectionReply)
	err := c.cc.Invoke(ctx, "/here.Student/ChooseSection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServer is the server API for Student service.
// All implementations must embed UnimplementedStudentServer
// for forward compatibility
type StudentServer interface {
	GetCourses(context.Context, *StudentRequest) (*GetCoursesReply, error)
	GetGrades(context.Context, *StudentRequest) (*GetGradesReply, error)
	SubmitSwapRequests(context.Context, *SwapRequest) (*emptypb.Empty, error)
	ChooseSection(context.Context, *ChooseSectionRequest) (*ChooseSectionReply, error)
	mustEmbedUnimplementedStudentServer()
}

// UnimplementedStudentServer must be embedded to have forward compatible implementations.
type UnimplementedStudentServer struct {
}

func (UnimplementedStudentServer) GetCourses(context.Context, *StudentRequest) (*GetCoursesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourses not implemented")
}
func (UnimplementedStudentServer) GetGrades(context.Context, *StudentRequest) (*GetGradesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrades not implemented")
}
func (UnimplementedStudentServer) SubmitSwapRequests(context.Context, *SwapRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSwapRequests not implemented")
}
func (UnimplementedStudentServer) ChooseSection(context.Context, *ChooseSectionRequest) (*ChooseSectionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseSection not implemented")
}
func (UnimplementedStudentServer) mustEmbedUnimplementedStudentServer() {}

// UnsafeStudentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServer will
// result in compilation errors.
type UnsafeStudentServer interface {
	mustEmbedUnimplementedStudentServer()
}

func RegisterStudentServer(s grpc.ServiceRegistrar, srv StudentServer) {
	s.RegisterService(&Student_ServiceDesc, srv)
}

func _Student_GetCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).GetCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/here.Student/GetCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).GetCourses(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_GetGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).GetGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/here.Student/GetGrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).GetGrades(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_SubmitSwapRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).SubmitSwapRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/here.Student/SubmitSwapRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).SubmitSwapRequests(ctx, req.(*SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Student_ChooseSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChooseSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServer).ChooseSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/here.Student/ChooseSection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServer).ChooseSection(ctx, req.(*ChooseSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Student_ServiceDesc is the grpc.ServiceDesc for Student service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Student_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "here.Student",
	HandlerType: (*StudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourses",
			Handler:    _Student_GetCourses_Handler,
		},
		{
			MethodName: "GetGrades",
			Handler:    _Student_GetGrades_Handler,
		},
		{
			MethodName: "SubmitSwapRequests",
			Handler:    _Student_SubmitSwapRequests_Handler,
		},
		{
			MethodName: "ChooseSection",
			Handler:    _Student_ChooseSection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/student.proto",
}
