// source: model/admin.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var model_general_pb = require('../model/general_pb.js');
goog.object.extend(proto, model_general_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.here.GetAllSectionsReply', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.here.GetAllSectionsReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.here.GetAllSectionsReply.repeatedFields_, null);
};
goog.inherits(proto.here.GetAllSectionsReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.here.GetAllSectionsReply.displayName = 'proto.here.GetAllSectionsReply';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.here.GetAllSectionsReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.here.GetAllSectionsReply.prototype.toObject = function(opt_includeInstance) {
  return proto.here.GetAllSectionsReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.here.GetAllSectionsReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.here.GetAllSectionsReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    sectionsList: jspb.Message.toObjectList(msg.getSectionsList(),
    model_general_pb.Section.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.here.GetAllSectionsReply}
 */
proto.here.GetAllSectionsReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.here.GetAllSectionsReply;
  return proto.here.GetAllSectionsReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.here.GetAllSectionsReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.here.GetAllSectionsReply}
 */
proto.here.GetAllSectionsReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new model_general_pb.Section;
      reader.readMessage(value,model_general_pb.Section.deserializeBinaryFromReader);
      msg.addSections(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.here.GetAllSectionsReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.here.GetAllSectionsReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.here.GetAllSectionsReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.here.GetAllSectionsReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSectionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      model_general_pb.Section.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Section sections = 1;
 * @return {!Array<!proto.Section>}
 */
proto.here.GetAllSectionsReply.prototype.getSectionsList = function() {
  return /** @type{!Array<!proto.Section>} */ (
    jspb.Message.getRepeatedWrapperField(this, model_general_pb.Section, 1));
};


/**
 * @param {!Array<!proto.Section>} value
 * @return {!proto.here.GetAllSectionsReply} returns this
*/
proto.here.GetAllSectionsReply.prototype.setSectionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Section=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Section}
 */
proto.here.GetAllSectionsReply.prototype.addSections = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Section, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.here.GetAllSectionsReply} returns this
 */
proto.here.GetAllSectionsReply.prototype.clearSectionsList = function() {
  return this.setSectionsList([]);
};


goog.object.extend(exports, proto.here);
