version: '3.8'

services:
  app:
    container_name: here
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1-bullseye"
        NODE_VERSION: "18"
    command: sleep infinity
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
      ALLOWED_EMAIL_DOMAINS: "brown.edu,gmail.com"
      IS_COOKIE_CROSS_SITE: "false"
      SERVER_PORT: "8000"
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    volumes:
      - ..:/workspaces/here:cached
